spring:
    cache:
        port: 6379
        host: 127.0.0.1
        #        password: AdZFxwlBmWU81qvKyz4E7ccYbrMyiHsX
        default-ttl: 180

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
        generate-ddl: true

    datasource:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/ussd_service?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            username: root
            password: